name: Daily Commit Workflow

on:
  schedule:
    - cron: '30 9 * * *'  # Runs at 9:30 AM UTC daily
  workflow_dispatch:       # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # Required for pushing commits
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0     # Fetches all history for proper git operations
        
    - name: Configure Git for 24f1001929@ds.study.iitm.ac.in
      run: |
        git config --global user.email "24f1001929@ds.study.iitm.ac.in"
        git config --global user.name "Daily Commit Bot"
        
    - name: Create daily commit file
      run: |
        mkdir -p daily-logs
        echo "Daily commit generated on $(date -u)" > daily-logs/daily-commit-$(date -u +%Y-%m-%d).txt
        echo "Workflow run number: ${{ github.run_number }}" >> daily-logs/daily-commit-$(date -u +%Y-%m-%d).txt
        
    - name: Commit and push changes
      run: |
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Daily automated commit - $(date -u +%Y-%m-%d)"
          git push origin HEAD:main
        fi
